services:
  - type: web
    name: quantitative-trading-model-web
    env: python
    buildCommand: pip install -r requirements.txt && cd frontend && npm ci --include=dev && npm run build
    startCommand: gunicorn app:app
